name: "Check GitHub Token"
description: "Check if GITHUB_TOKEN environment variable exists"
author: "Pullfrog"

inputs:
  token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  anthropic_key:
    description: "Anthropic API key"
    required: false
    default: ${{ secrets.ANTHROPIC_API_KEY }}

runs:
  using: "node24"
  main: "entry.ts"
